# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modifyname.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_modifyname(object):
    def setupUi(self, modifyname):
        modifyname.setObjectName("modifyname")
        modifyname.resize(701, 205)
        self.pushButton = QtWidgets.QPushButton(modifyname)
        self.pushButton.setGeometry(QtCore.QRect(310, 140, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(modifyname)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(130, 30, 471, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(modifyname)
        self.label.setGeometry(QtCore.QRect(70, 30, 51, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(modifyname)
        self.label_2.setGeometry(QtCore.QRect(70, 80, 51, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(modifyname)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 80, 471, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(modifyname)
        QtCore.QMetaObject.connectSlotsByName(modifyname)

    def retranslateUi(self, modifyname):
        _translate = QtCore.QCoreApplication.translate
        modifyname.setWindowTitle(_translate("modifyname", "Dialog"))
        self.pushButton.setText(_translate("modifyname", "确定"))
        self.label.setText(_translate("modifyname", "旧名字："))
        self.label_2.setText(_translate("modifyname", "新名字："))
