# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'normalize.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_normalize(object):
    def setupUi(self, normalize):
        normalize.setObjectName("normalize")
        normalize.resize(400, 300)

        self.retranslateUi(normalize)
        QtCore.QMetaObject.connectSlotsByName(normalize)

    def retranslateUi(self, normalize):
        _translate = QtCore.QCoreApplication.translate
        normalize.setWindowTitle(_translate("normalize", "Form"))
